server:
  port: 80
  servlet:
    multipart:
    encoding:
      charset: utf-8
      force: true
    session:
      cookie:
        name: sessionId
      timeout: 0
  error:
    path: /templates/module/bms/error/error.htm
  tomcat:
    basedir: logs/tomcat
#-----------------------------------------------
spring:
  main:
    allow-circular-references: true
    banner-mode: console
  banner:
    charset: UTF-8
    location: classpath:/public/startup/1002.txt
  web:
    resources:
      static-locations: classpath:/public/,classpath:/static/,file:D:\dev\map
##############数据库配置部分###############################
#主数据源名称为 datasource ；不允许更改
datasource:
  main:
    dbname: datasource
jdbc:
  type: mysql
  url: jdbc:mysql://119.189.0.152:3306/academic?useUnicode=true&useSSL=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
  username: root
  password: ldonglit1q!
  driver: com.mysql.cj.jdbc.Driver

#部署环境配置
academic:
  local:
    ktrPath: C:\dev\bsdms\sql
    baseUrl: http://www.bsdms.org
    upload:
      path: C:\dev\bsdms\upload
    download:
      path: C:\dev\bsdms\download
    sql:
      path: C:\dev\bsdms\sql\nodeInit.sql